import { Dimensions, StyleSheet } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const BASE_WIDTH = 390;
const BASE_HEIGHT = 844;

const clamp = (min: number, value: number, max: number) => Math.min(max, Math.max(min, value));

const widthRatio = SCREEN_WIDTH / BASE_WIDTH;
const heightRatio = SCREEN_HEIGHT / BASE_HEIGHT;

const scaleSize = (size: number, minScale = 0.88, maxScale = 1.2) =>
  Math.round(size * clamp(minScale, widthRatio, maxScale));
const scaleVertical = (size: number, minScale = 0.88, maxScale = 1.2) =>
  Math.round(size * clamp(minScale, heightRatio, maxScale));
const scaleFont = (size: number, minScale = 0.9, maxScale = 1.16) =>
  Math.round(size * clamp(minScale, widthRatio, maxScale));

const IS_COMPACT = SCREEN_WIDTH <= 360;
const IS_TABLET = SCREEN_WIDTH >= 768;

const TWO_COLUMN_CARD_WIDTH = IS_COMPACT ? '100%' : IS_TABLET ? '31.8%' : '48.6%';
const PRODUCT_TILE_WIDTH = IS_COMPACT ? '100%' : IS_TABLET ? '32%' : '48.6%';
const CATEGORY_CARD_WIDTH = IS_COMPACT ? scaleSize(102, 0.9, 1.1) : scaleSize(112, 0.95, 1.15);
const BROWSE_CATEGORY_CARD_WIDTH = IS_COMPACT ? '100%' : IS_TABLET ? '31.8%' : '48.6%';
const CATEGORY_PRODUCTS_CARD_WIDTH = IS_TABLET ? '31.8%' : '48.6%';
const HERO_HEADLINE_WIDTH = IS_COMPACT ? '86%' : IS_TABLET ? '58%' : '74%';

const styles = StyleSheet.create({
  safe: { flex: 1 },
  top: {
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topActions: { flexDirection: 'row', gap: 8 },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
  },
  brandLogo: {
    width: scaleSize(140),
    height: scaleVertical(36),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  brandLogoImage: {
    width: '100%',
    height: '100%',
  },
  headerIconBtn: {
    width: scaleSize(34),
    height: scaleSize(34),
    borderRadius: scaleSize(17),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF2F7',
  },
  // Shared accent style for header action icons (reuse for future icon buttons).
  headerIconBtnPrimary: {
    backgroundColor: '#1E7B39',
  },
  headerIconText: {
    fontSize: scaleFont(17),
    lineHeight: scaleFont(18),
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  headerIconTextPrimary: {
    color: '#FFFFFF',
  },
  headerIconTextAccent: {
    color: '#1E7B39',
  },
  brand: { fontSize: scaleFont(22), fontWeight: '800' },
  title: { fontSize: scaleFont(17), fontWeight: '800' },
  small: { fontSize: scaleFont(11), fontWeight: '600' },
  pickerLabel: {
    marginBottom: 6,
  },
  fieldLabel: {
    marginBottom: 4,
    marginLeft: 2,
  },
  toast: {
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  toastText: {
    color: '#F8FAFC',
    fontSize: scaleFont(12),
    fontWeight: '700',
  },
  poweredByFooter: {
    marginTop: 16,
    paddingTop: 12,
    paddingBottom: 6,
    paddingHorizontal: 12,
    borderTopWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  poweredByFooterFloating: {
    marginTop: 0,
    marginHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 2,
  },
  poweredByFooterText: {
    fontSize: scaleFont(10),
    lineHeight: scaleFont(14),
    fontWeight: '700',
    letterSpacing: 0.35,
    textAlign: 'center',
  },
  headerLoginBtn: {
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#1E7B39',
    backgroundColor: '#FFFFFF',
  },
  headerLoginBtnText: {
    color: '#1E7B39',
    fontSize: scaleFont(11),
    fontWeight: '800',
  },
  adminNavChipActive: {
    borderWidth: 1,
    borderColor: '#1E7B39',
    backgroundColor: '#FFFFFF',
  },
  adminNavChipInactive: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#F8FAF7',
  },
  adminNavChipTextActive: {
    color: '#1E7B39',
  },
  pickerChipSelectedOutlined: {
    borderWidth: 1,
    borderColor: '#1E7B39',
    backgroundColor: '#FFFFFF',
  },
  pickerChipUnselectedOutlined: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#F8FAF7',
  },
  pickerChipTextSelectedOutlined: {
    color: '#1E7B39',
  },
  orderSubmitBtn: {
    borderWidth: 1,
    borderColor: '#1E7B39',
    backgroundColor: '#1E7B39',
  },
  orderSubmitBtnDisabled: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#CBD5E1',
  },
  orderSubmitBtnText: {
    color: '#FFFFFF',
  },
  orderSubmitBtnTextDisabled: {
    color: '#FFFFFF',
  },
  authModalSafe: {
    flex: 1,
    backgroundColor: '#F0F3F5',
  },
  authModalContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  authModalTop: {
    paddingTop: 8,
    paddingBottom: 8,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  authBackBtn: {
    width: scaleSize(34),
    height: scaleSize(34),
    borderRadius: scaleSize(17),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
  },
  authBackText: {
    color: '#0F172A',
    fontSize: scaleFont(19),
    fontWeight: '900',
    lineHeight: scaleFont(20),
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  authBrandRow: {
    marginTop: 4,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0,
  },
  authBrandLogo: {
    width: scaleSize(210, 0.88, 1.15),
    height: scaleVertical(54, 0.9, 1.12),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  authBrandLogoImage: {
    width: '100%',
    height: '100%',
  },
  authBrandText: {
    color: '#111827',
    fontSize: scaleFont(22),
    fontWeight: '900',
  },
  authBrandSub: {
    color: '#374151',
    fontSize: scaleFont(16),
    letterSpacing: 3,
    fontWeight: '600',
  },
  authCard: {
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 14,
    shadowColor: '#0F172A',
    shadowOpacity: 0.09,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  authTitle: {
    color: '#063B2F',
    fontSize: scaleFont(26),
    lineHeight: scaleFont(32),
    fontWeight: '900',
    textAlign: 'center',
  },
  authSubtitle: {
    color: '#374151',
    fontSize: scaleFont(16),
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 4,
    marginBottom: 14,
  },
  authEntryNotice: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  authEntryNoticeText: {
    fontSize: scaleFont(13),
    lineHeight: scaleFont(18),
    fontWeight: '700',
    textAlign: 'center',
  },
  authInputWrap: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    marginBottom: 10,
    minHeight: 52,
    shadowColor: '#0F172A',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  authInputIcon: {
    width: scaleSize(24),
    textAlign: 'center',
    color: '#1E7B39',
    fontSize: scaleFont(18),
    marginRight: 6,
  },
  authInputField: {
    flex: 1,
    color: '#111827',
    fontSize: scaleFont(16),
    fontWeight: '600',
    paddingVertical: 12,
  },
  authHint: {
    color: '#6B7280',
    fontSize: scaleFont(12),
    fontWeight: '600',
    marginTop: -2,
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  authForgot: {
    color: '#111827',
    fontSize: scaleFont(15),
    fontWeight: '600',
    textAlign: 'right',
    marginBottom: 12,
  },
  authPrimaryBtn: {
    borderRadius: 20,
    backgroundColor: '#1E7B39',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 56,
    shadowColor: '#14532D',
    shadowOpacity: 0.28,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  authPrimaryText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
  authSwitchRow: {
    marginTop: 14,
    alignItems: 'center',
  },
  authSwitchText: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '500',
  },
  authSwitchLink: {
    color: '#0E7A33',
    fontWeight: '900',
  },
  authDividerRow: {
    marginTop: 14,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  authDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#CBD5E1',
  },
  authDividerText: {
    color: '#1F2937',
    fontSize: 13,
    fontWeight: '600',
  },
  authSocialBtn: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 10,
  },
  authSocialEmoji: {
    color: '#EA4335',
    fontSize: 32,
    fontWeight: '900',
    lineHeight: 34,
  },
  authSocialText: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '900',
  },
  authSocialBtnFb: {
    borderRadius: 18,
    backgroundColor: '#1D4E9B',
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 2,
    shadowColor: '#1D4E9B',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  authSocialEmojiFb: {
    color: '#FFFFFF',
    fontSize: 38,
    fontWeight: '900',
    lineHeight: 40,
    marginTop: -2,
  },
  authSocialTextFb: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  authBottomVisual: {
    marginTop: 14,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: '#DDE7D7',
  },
  authBottomImage: {
    width: '100%',
    height: scaleVertical(210, 0.86, 1.12),
  },
  loginCard: {
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  updateModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2, 6, 23, 0.58)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  updateModalCard: {
    width: '100%',
    maxWidth: 460,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 10,
  },
  updateModalEyebrow: {
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  updateModalTitle: {
    fontSize: scaleFont(26, 0.88, 1.04),
    lineHeight: scaleFont(29, 0.88, 1.04),
    fontWeight: '900',
  },
  updateModalSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  updateModalMeta: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  updateModalNotesCard: {
    marginTop: 2,
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    gap: 6,
  },
  updateModalNotesLabel: {
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  updateModalNotesText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  updateModalProgressWrap: {
    marginTop: 2,
    gap: 8,
  },
  updateModalProgressTrack: {
    height: 10,
    borderRadius: 999,
    overflow: 'hidden',
  },
  updateModalProgressFill: {
    height: '100%',
    borderRadius: 999,
  },
  updateModalProgressMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  updateModalProgressLabel: {
    flex: 1,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '800',
  },
  updateModalProgressValue: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
  },
  updateModalProgressMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  updateModalError: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  updateModalActions: {
    marginTop: 6,
    flexDirection: 'row',
    gap: 10,
  },
  updateModalPrimaryBtn: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  updateModalPrimaryText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  updateModalSecondaryBtn: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  updateModalSecondaryText: {
    fontSize: 15,
    fontWeight: '800',
  },
  locationSearchWrap: {
    marginTop: -2,
    borderRadius: 14,
    padding: 10,
    gap: 8,
  },
  stickySearchWrap: {
    marginTop: scaleVertical(6, 0.88, 1.2),
    borderRadius: 14,
    padding: 10,
    zIndex: 3,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  locationPin: {
    fontSize: scaleFont(22),
  },
  locationText: {
    fontSize: scaleFont(17),
    fontWeight: '900',
    lineHeight: scaleFont(19),
  },
  searchInput: {
    borderRadius: 20,
    paddingHorizontal: 13,
    paddingVertical: 10,
    fontSize: scaleFont(13),
    fontWeight: '600',
  },
  locationSearchInputWrap: {
    position: 'relative',
    justifyContent: 'center',
  },
  searchInputWithClear: {
    paddingRight: 44,
  },
  searchClearBtn: {
    position: 'absolute',
    right: 10,
    width: scaleSize(26),
    height: scaleSize(26),
    borderRadius: scaleSize(13),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF2F7',
  },
  searchClearBtnText: {
    color: '#334155',
    fontSize: scaleFont(13),
    fontWeight: '900',
    lineHeight: scaleFont(15),
  },
  locationModalSafe: {
    flex: 1,
    backgroundColor: '#F3F6F3',
  },
  locationModalHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#1E7B39',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  locationModalBack: {
    color: '#FFFFFF',
    fontSize: scaleFont(25),
    fontWeight: '800',
    lineHeight: scaleFont(25),
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  locationModalTitle: {
    color: '#FFFFFF',
    fontSize: scaleFont(20),
    fontWeight: '900',
  },
  locationModalSearchWrap: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  detectBtn: {
    borderRadius: 12,
    backgroundColor: '#EFF9F1',
    borderWidth: 1,
    borderColor: '#87CC98',
    alignItems: 'center',
    paddingVertical: 11,
  },
  detectBtnContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detectBtnText: {
    color: '#166534',
    fontSize: 16,
    fontWeight: '800',
  },
  locationSearchLoaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 4,
  },
  locationSearchLoaderText: {
    color: '#166534',
    fontSize: 12,
    fontWeight: '700',
  },
  detectNetworkBtn: {
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    paddingVertical: 10,
  },
  detectNetworkBtnText: {
    color: '#1F2937',
    fontSize: 15,
    fontWeight: '700',
  },
  locationModalContent: {
    paddingHorizontal: 12,
    paddingBottom: 12,
  },
  locationSectionTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1F2937',
    marginBottom: 8,
  },
  locationSectionGap: {
    height: 12,
  },
  locationRowCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
  },
  locationRowCardActive: {
    borderColor: '#22A447',
    backgroundColor: '#EFFAF2',
  },
  locationRowTitle: {
    color: '#111827',
    fontSize: 17,
    fontWeight: '900',
  },
  locationRowSub: {
    color: '#6B7280',
    fontSize: 14,
    marginTop: 2,
    fontWeight: '600',
  },
  seeMoreBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    paddingVertical: 9,
    marginBottom: 8,
  },
  seeMoreBtnText: {
    color: '#1F2937',
    fontSize: 14,
    fontWeight: '700',
  },
  locationBottomActions: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#F3F6F3',
  },
  saveAddrBtn: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#9CA3AF',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    paddingVertical: 12,
  },
  saveAddrBtnText: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  applyLocationBtn: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: '#1E8C28',
    alignItems: 'center',
    paddingVertical: 12,
  },
  applyLocationBtnText: {
    color: '#FFFFFF',
    fontSize: scaleFont(16),
    fontWeight: '900',
  },
  heroLanding: {
    borderRadius: 16,
    height: scaleVertical(320, 0.84, 1.08),
    backgroundColor: '#133527',
    overflow: 'hidden',
    shadowColor: '#1F2937',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  heroContent: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 22,
    paddingBottom: 16,
    justifyContent: 'space-between',
  },
  heroTopText: {
    color: '#E7F6EF',
    fontSize: scaleFont(17),
    fontWeight: '700',
    textAlign: 'left',
  },
  heroMain: {
    color: '#FFFFFF',
    fontSize: scaleFont(43, 0.78, 1.04),
    lineHeight: scaleFont(45, 0.78, 1.04),
    fontWeight: '900',
    textAlign: 'left',
    width: HERO_HEADLINE_WIDTH,
  },
  heroBgImage: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    marginLeft: 0,
    marginTop: 0,
    backgroundColor: '#4F8A57',
  },
  heroOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(5, 20, 34, 0.46)',
  },
  heroFallbackWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: '#DDE7D7',
    padding: 12,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-end',
  },
  heroFallbackInverter: {
    flex: 1,
    height: scaleVertical(92, 0.88, 1.1),
    borderRadius: 10,
    backgroundColor: '#C8D8C4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroFallbackBattery: {
    flex: 1,
    height: scaleVertical(132, 0.88, 1.1),
    borderRadius: 10,
    backgroundColor: '#F5F7F3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroFallbackText: {
    color: '#111827',
    fontSize: scaleFont(12),
    fontWeight: '800',
  },
  heroActions: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 8,
  },
  shopNowHeroBtn: {
    alignSelf: 'flex-start',
    minWidth: scaleSize(166, 0.82, 1.15),
    borderRadius: 999,
    backgroundColor: '#3A8D12',
    paddingHorizontal: 24,
    paddingVertical: 12,
    alignItems: 'center',
    shadowColor: '#0F4D1D',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  shopNowHeroText: {
    color: '#FFFFFF',
    fontSize: scaleFont(18),
    fontWeight: '900',
  },
  trustStrip: {
    borderRadius: 12,
    paddingVertical: 11,
    paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  trustItem: {
    width: '31%',
    alignItems: 'center',
    gap: 4,
  },
  trustIcon: {
    fontSize: scaleFont(21),
  },
  heroActionBtn: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  heroActionText: {
    color: '#FFFFFF',
    fontSize: scaleFont(13),
    fontWeight: '900',
  },
  categoryBar: {
    borderRadius: 12,
    flexDirection: 'row',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#D1D5DB',
  },
  categoryItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 11,
    borderRightWidth: 1,
    borderRightColor: '#D1D5DB',
  },
  categoryIcon: {
    fontSize: scaleFont(28),
    marginBottom: 3,
  },
  categoryLabel: {
    fontSize: scaleFont(12),
    fontWeight: '800',
    color: '#1F2937',
  },
  categoryScroll: {
    flexDirection: 'row',
    gap: 10,
  },
  categoryCardNew: {
    width: CATEGORY_CARD_WIDTH,
    borderRadius: 12,
    padding: 8,
    alignItems: 'center',
    backgroundColor: '#F4F7F4',
    borderColor: '#E5E7EB',
    borderWidth: 1,
  },
  categoryCardNewDark: {
    backgroundColor: '#111827',
    borderColor: '#334155',
  },
  categoryCardNewDarkActive: {
    borderColor: '#3FA36A',
    borderWidth: 1.5,
  },
  categoryThumb: {
    width: '100%',
    height: scaleVertical(54, 0.9, 1.15),
    borderRadius: 9,
    backgroundColor: '#E6ECE2',
  },
  categoryThumbDark: {
    backgroundColor: '#1F2937',
    opacity: 0.78,
  },
  categoryIconSmall: {
    marginTop: -10,
    fontSize: scaleFont(17),
  },
  categoryIconSmallDark: {
    opacity: 0.88,
  },
  browseCategoriesWrap: {
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingTop: 14,
    paddingBottom: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: '#D9DEE6',
    shadowColor: '#1E293B',
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
  },
  browseCategoriesTitle: {
    textAlign: 'center',
    fontSize: scaleFont(24, 0.86, 1.05),
    fontWeight: '900',
    color: '#0F1F3A',
    letterSpacing: 0.1,
  },
  browseCategoriesDivider: {
    height: 1,
    opacity: 0.75,
    marginHorizontal: -12,
  },
  browseCategoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  browseCategoryCard: {
    width: BROWSE_CATEGORY_CARD_WIDTH,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingTop: 12,
    paddingBottom: 12,
    alignItems: 'center',
    gap: 8,
    shadowColor: '#64748B',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  browseCategoryBrand: {
    fontSize: scaleFont(17, 0.88, 1.05),
    fontWeight: '900',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  browseCategoryImage: {
    width: '100%',
    height: scaleVertical(112, 0.9, 1.06),
  },
  browseCategoryName: {
    textAlign: 'center',
    fontSize: scaleFont(14),
    fontWeight: '700',
  },
  browseCategoryExploreBtn: {
    marginTop: 2,
    alignSelf: 'center',
    borderRadius: 999,
    minWidth: scaleSize(96, 0.9, 1.08),
    paddingHorizontal: 16,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3A8D12',
    shadowColor: '#0F4D1D',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  browseCategoryExploreText: {
    color: '#FFFFFF',
    fontSize: scaleFont(12),
    fontWeight: '800',
  },
  categoryProductsPageWrap: {
    width: '100%',
    paddingHorizontal: 2,
    paddingVertical: 4,
    gap: 12,
  },
  categoryProductsTopBar: {
    borderBottomWidth: 0,
    borderRadius: 12,
    borderWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  categoryProductsIconBtn: {
    width: scaleSize(34),
    height: scaleSize(34),
    borderRadius: scaleSize(17),
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryProductsIcon: {
    color: '#6B7280',
    fontSize: scaleFont(20),
    fontWeight: '700',
    lineHeight: scaleFont(20),
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  categoryProductsBrandPill: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 0,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    justifyContent: 'center',
  },
  categoryProductsBrandPillText: {
    color: '#5F9D67',
    fontSize: scaleFont(19, 0.9, 1.02),
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  categoryProductsBreadcrumb: {
    marginTop: 1,
    paddingHorizontal: 2,
    fontSize: scaleFont(12),
    fontWeight: '600',
  },
  categoryProductsHero: {
    borderRadius: 16,
    borderWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#F4F7FB',
  },
  categoryProductsHeroTextWrap: {
    flex: 1,
    gap: 5,
  },
  categoryProductsHeroBrand: {
    color: '#5F9D67',
    fontSize: scaleFont(24, 0.88, 1.03),
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  categoryProductsHeroTitle: {
    fontSize: scaleFont(17),
    fontWeight: '900',
    lineHeight: scaleFont(21),
  },
  categoryProductsHeroSubline: {
    fontSize: scaleFont(11),
    lineHeight: scaleFont(16),
    fontWeight: '600',
  },
  categoryProductsHeroBtn: {
    marginTop: 6,
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#5F9D67',
    minWidth: scaleSize(96, 0.9, 1.08),
    paddingHorizontal: 16,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#123F79',
    shadowOpacity: 0.24,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  categoryProductsHeroBtnText: {
    color: '#FFFFFF',
    fontSize: scaleFont(12),
    fontWeight: '800',
  },
  categoryProductsHeroImage: {
    width: IS_COMPACT ? '42%' : '45%',
    height: scaleVertical(128, 0.85, 1.06),
  },
  categoryProductsSectionTitle: {
    fontSize: scaleFont(17),
    fontWeight: '800',
  },
  categoryProductsSortPill: {
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  categoryProductsSortLabel: {
    fontSize: scaleFont(11),
    fontWeight: '600',
  },
  categoryProductsSortValue: {
    fontSize: scaleFont(13),
    fontWeight: '700',
  },
  categoryProductsFilterBtn: {
    alignSelf: 'flex-start',
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  categoryProductsFilterBtnText: {
    fontSize: scaleFont(12),
    fontWeight: '700',
  },
  categoryProductsSearchWrap: {
    borderRadius: 12,
    borderWidth: 1,
    minHeight: scaleVertical(42, 0.9, 1.08),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    gap: 6,
  },
  categoryProductsSearchIcon: {
    fontSize: scaleFont(14),
    fontWeight: '700',
  },
  categoryProductsSearchInput: {
    flex: 1,
    fontSize: scaleFont(14),
    fontWeight: '600',
    paddingVertical: 9,
  },
  categoryProductsSearchClear: {
    fontSize: scaleFont(14),
    fontWeight: '800',
    paddingHorizontal: 4,
  },
  categoryProductsSearchStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 2,
  },
  categoryProductsSearchStatusText: {
    flex: 1,
    fontSize: scaleFont(12),
    fontWeight: '600',
  },
  categoryProductsSearchStatusClear: {
    fontSize: scaleFont(12),
    fontWeight: '800',
  },
  categoryProductsSearchModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2, 6, 23, 0.42)',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  categoryProductsSearchModalCard: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 12,
    gap: 10,
  },
  categoryProductsSearchModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categoryProductsSearchModalTitle: {
    fontSize: scaleFont(15),
    fontWeight: '800',
  },
  categoryProductsSearchModalDone: {
    fontSize: scaleFont(13),
    fontWeight: '800',
  },
  categoryProductsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 16,
  },
  categoryProductsCard: {
    width: CATEGORY_PRODUCTS_CARD_WIDTH,
    borderRadius: 0,
    borderWidth: 0,
    borderBottomWidth: 1,
    paddingHorizontal: 4,
    paddingVertical: 10,
    alignItems: 'center',
    gap: 7,
    minHeight: scaleVertical(228, 0.86, 1.08),
  },
  categoryProductsCardImage: {
    width: '100%',
    height: scaleVertical(110, 0.9, 1.05),
  },
  categoryProductsCardImageDark: {
    backgroundColor: '#1F2937',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
    opacity: 0.84,
  },
  categoryProductsCardName: {
    textAlign: 'center',
    fontSize: scaleFont(13),
    fontWeight: '700',
    lineHeight: scaleFont(17),
    minHeight: scaleVertical(35, 0.9, 1.1),
  },
  categoryProductsCardModel: {
    textAlign: 'center',
    fontSize: scaleFont(11),
    fontWeight: '600',
    minHeight: scaleVertical(16, 0.9, 1.1),
  },
  categoryProductsCardBtn: {
    marginTop: 'auto',
    borderRadius: 999,
    backgroundColor: '#5F9D67',
    minWidth: scaleSize(96, 0.9, 1.08),
    paddingHorizontal: 16,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#123F79',
    shadowOpacity: 0.24,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  categoryProductsCardBtnText: {
    color: '#FFFFFF',
    fontSize: scaleFont(12),
    fontWeight: '800',
  },
  categoryProductsPagerRow: {
    marginTop: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  categoryProductsPagerBtn: {
    width: scaleSize(32),
    height: scaleSize(32),
    borderRadius: 10,
    backgroundColor: '#EEF2F7',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryProductsPagerBtnDisabled: {
    opacity: 0.45,
  },
  categoryProductsPagerBtnText: {
    color: '#334155',
    fontSize: scaleFont(18),
    fontWeight: '700',
    lineHeight: scaleFont(18),
  },
  categoryProductsPagerBtnTextDisabled: {
    color: '#94A3B8',
  },
  categoryProductsPagerNum: {
    minWidth: scaleSize(32),
    height: scaleSize(32),
    borderRadius: 10,
    backgroundColor: '#EEF2F7',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  categoryProductsPagerNumActive: {
    backgroundColor: '#5F9D67',
  },
  categoryProductsPagerNumText: {
    color: '#334155',
    fontSize: scaleFont(12),
    fontWeight: '700',
  },
  categoryProductsPagerNumTextActive: {
    color: '#FFFFFF',
  },
  card: {
    borderRadius: 14,
    padding: 12,
    gap: 10,
  },
  form: {
    borderRadius: 10,
    padding: 10,
    gap: 8,
  },
  row: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  navSliderRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    paddingRight: 8,
    flexWrap: 'nowrap',
  },
  navSliderChip: {
    flexShrink: 0,
  },
  adminNavChip: {
    flexShrink: 0,
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminNavChipLight: {
    backgroundColor: '#F4F7F4',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#64748B',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  adminNavChipLightActive: {
    backgroundColor: '#F8FAF7',
    borderWidth: 2,
    borderColor: '#5F9D67',
    shadowColor: '#3E7B53',
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  adminNavChipDark: {
    backgroundColor: '#334155',
    borderWidth: 1,
    borderColor: '#334155',
  },
  adminNavChipDarkActive: {
    backgroundColor: '#60A5FA',
    borderWidth: 1,
    borderColor: '#60A5FA',
  },
  adminNavChipText: {
    fontSize: scaleFont(12),
    fontWeight: '800',
    letterSpacing: 0.1,
  },
  adminNavChipTextLightActive: {
    color: '#225C3D',
  },
  adminNavChipTextDarkActive: {
    color: '#FFFFFF',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemTagRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  itemTagChip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderWidth: 1,
  },
  itemTagChipText: {
    fontSize: scaleFont(12),
    fontWeight: '700',
  },
  itemImageUploadBtn: {
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  itemImageUploadBtnText: {
    fontSize: scaleFont(12),
    fontWeight: '700',
  },
  itemUrlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  itemUrlInput: {
    flex: 1,
  },
  itemUrlActionBtn: {
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  itemUrlActionBtnText: {
    fontSize: scaleFont(12),
    fontWeight: '700',
  },
  itemUrlRemoveBtn: {
    alignSelf: 'center',
  },
  itemUrlRemoveBtnText: {
    fontSize: scaleFont(11),
    fontWeight: '700',
    color: '#B91C1C',
  },
  itemImagePreviewRow: {
    gap: 8,
    paddingTop: 2,
    paddingBottom: 4,
  },
  itemImagePreviewCard: {
    width: scaleSize(120, 0.85, 1.1),
    borderRadius: 10,
    padding: 6,
    gap: 6,
  },
  itemImagePreviewImage: {
    width: '100%',
    height: scaleVertical(80, 0.85, 1.1),
    borderRadius: 8,
    backgroundColor: '#D1D5DB',
  },
  itemImageRemoveBtn: {
    alignSelf: 'flex-end',
  },
  itemImageRemoveBtnText: {
    fontSize: scaleFont(11),
    fontWeight: '700',
    color: '#B91C1C',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stat: {
    width: TWO_COLUMN_CARD_WIDTH,
    borderRadius: 8,
    padding: 10,
  },
  input: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 9,
    fontSize: scaleFont(13),
    fontWeight: '600',
  },
  brandInputWrap: {
    zIndex: 10,
  },
  brandDropdown: {
    marginTop: 4,
    borderRadius: 10,
    borderWidth: 1,
    maxHeight: 220,
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  brandDropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  brandDropdownItemLast: {
    paddingBottom: 7,
    marginBottom: 0,
  },
  brandDropdownText: {
    fontSize: scaleFont(13),
    fontWeight: '700',
  },
  brandDropdownDivider: {
    height: 1,
  },
  brandDropdownManualText: {
    fontSize: scaleFont(13),
    fontWeight: '800',
    color: '#1E7B39',
  },
  half: { flex: 1 },
  primaryBtn: {
    borderRadius: 9,
    paddingVertical: 10,
    alignItems: 'center',
  },
  primaryText: { color: '#0B1220', fontSize: scaleFont(13), fontWeight: '900' },
  chip: {
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  chipText: { fontSize: scaleFont(11), fontWeight: '800' },
  rowCard: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  itemEditIconBtn: {
    width: scaleSize(30),
    height: scaleSize(30),
    borderRadius: scaleSize(15),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E8F5EC',
  },
  itemEditIconText: {
    color: '#166534',
    fontSize: scaleFont(15),
    fontWeight: '900',
    lineHeight: scaleFont(16),
  },
  itemEditIconTextDisabled: {
    color: '#9CA3AF',
  },
  listItemSeparator: {
    height: 8,
  },
  productsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  featuredProductsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 8,
    columnGap: 8,
  },
  productTile: {
    width: PRODUCT_TILE_WIDTH,
    borderRadius: 10,
    padding: 9,
    gap: 5,
    minHeight: scaleVertical(210, 0.84, 1.06),
    borderWidth: 1,
    borderColor: '#D6DCE3',
    position: 'relative',
  },
  featuredProductTile: {
    width: '48.5%',
  },
  productTileName: {
    minHeight: scaleVertical(34, 0.9, 1.12),
  },
  productImage: {
    width: '100%',
    height: scaleVertical(92, 0.86, 1.12),
    borderRadius: 8,
    backgroundColor: '#E6ECE2',
  },
  productImageDark: {
    backgroundColor: '#1F2937',
    borderWidth: 1,
    borderColor: '#334155',
    opacity: 0.84,
  },
  productTileTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 5,
  },
  productFooter: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tileAction: {
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  tileActionText: {
    fontSize: scaleFont(11),
    fontWeight: '800',
  },
  dealBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 2,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  dealBadgeText: {
    color: '#FFFFFF',
    fontSize: scaleFont(10),
    fontWeight: '900',
  },
  cardDiscountStrip: {
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 3,
    minWidth: scaleSize(70, 0.88, 1.05),
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 12,
    borderWidth: 1,
  },
  cardDiscountStripLight: {
    backgroundColor: '#E6F7EB',
    borderColor: '#B8E2C5',
  },
  cardDiscountStripDark: {
    backgroundColor: '#153929',
    borderColor: '#1F6A53',
  },
  cardDiscountStripText: {
    fontSize: scaleFont(10),
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  cardDiscountStripTextLight: {
    color: '#166534',
  },
  cardDiscountStripTextDark: {
    color: '#86EFAC',
  },
  productInCartBadge: {
    marginTop: 2,
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  productInCartBadgeText: {
    color: '#166534',
    fontSize: scaleFont(11),
    fontWeight: '800',
  },
  shopTileBtn: {
    marginTop: 'auto',
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: 'center',
    backgroundColor: '#3F8F1D',
  },
  shopTileBtnText: {
    color: '#FFFFFF',
    fontSize: scaleFont(15),
    fontWeight: '900',
  },
  productListRow: {
    borderRadius: 10,
    padding: 9,
    flexDirection: 'row',
    gap: 9,
    alignItems: 'center',
  },
  productListImage: {
    width: scaleSize(74, 0.86, 1.1),
    height: scaleSize(74, 0.86, 1.1),
    borderRadius: 8,
    backgroundColor: '#E6ECE2',
  },
  productListImageDark: {
    backgroundColor: '#1F2937',
    borderWidth: 1,
    borderColor: '#334155',
    opacity: 0.84,
  },
  productCartHint: {
    color: '#166534',
    fontSize: scaleFont(11),
    fontWeight: '700',
    marginTop: 2,
  },
  offerSearchMeta: {
    marginTop: 2,
    marginBottom: 8,
  },
  offerPaginationRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  offerPaginationBtn: {
    minWidth: 96,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerPaginationBtnDisabled: {
    opacity: 0.55,
  },
  offerPaginationBtnText: {
    fontSize: scaleFont(12),
    fontWeight: '800',
  },
  offerPaginationText: {
    flex: 1,
    textAlign: 'center',
    fontSize: scaleFont(12),
    fontWeight: '700',
  },
  detailImage: {
    width: IS_COMPACT ? '100%' : scaleSize(240, 0.86, 1.05),
    height: scaleVertical(160, 0.86, 1.08),
    borderRadius: 10,
    backgroundColor: '#E6ECE2',
  },
  detailScreenWrap: {
    flex: 1,
    borderRadius: 0,
    overflow: 'hidden',
  },
  detailModalSafe: {
    flex: 1,
    backgroundColor: '#DDEEDF',
  },
  detailModalContent: {
    flexGrow: 1,
  },
  detailHero: {
    height: scaleVertical(250, 0.84, 1.1),
    position: 'relative',
  },
  detailHeroCarousel: {
    width: '100%',
    height: '100%',
  },
  detailHeroSlide: {
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
  },
  detailHeroImage: {
    width: '100%',
    height: '100%',
  },
  detailHeroOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(16, 50, 28, 0.20)',
  },
  detailTopActions: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detailCircleBtn: {
    width: scaleSize(40),
    height: scaleSize(40),
    borderRadius: scaleSize(20),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.93)',
  },
  detailCircleIcon: {
    fontSize: scaleFont(21),
    color: '#111827',
    fontWeight: '700',
    lineHeight: scaleFont(21),
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  detailImageCountPill: {
    position: 'absolute',
    left: 14,
    bottom: 14,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    minWidth: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailImageCountText: {
    fontSize: scaleFont(13),
    fontWeight: '800',
  },
  detailImageDotsRow: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  detailImageDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  detailImageDotActive: {
    width: 18,
  },
  bestsellerTag: {
    position: 'absolute',
    right: 14,
    bottom: 10,
    backgroundColor: '#F4E6A7',
    borderRadius: 999,
    paddingHorizontal: 13,
    paddingVertical: 7,
  },
  bestsellerTagText: {
    color: '#7C5C06',
    fontWeight: '800',
    fontSize: scaleFont(13),
  },
  detailSheet: {
    marginTop: -20,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  detailTitle: {
    fontSize: scaleFont(41, 0.8, 1.04),
    lineHeight: scaleFont(43, 0.8, 1.04),
    fontWeight: '900',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  ratingStar: {
    color: '#EAB308',
    fontSize: scaleFont(17),
    lineHeight: scaleFont(17),
  },
  ratingText: {
    fontSize: scaleFont(16),
    fontWeight: '800',
  },
  premiumPill: {
    marginLeft: 'auto',
    borderRadius: 999,
    backgroundColor: '#EEDC98',
    paddingHorizontal: 11,
    paddingVertical: 5,
  },
  premiumPillText: {
    color: '#8A6510',
    fontWeight: '800',
    fontSize: 16,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailPrice: {
    fontSize: 36,
    lineHeight: 38,
    fontWeight: '900',
  },
  detailMrp: {
    color: '#6B7280',
    textDecorationLine: 'line-through',
    fontSize: 20,
    lineHeight: 22,
    fontWeight: '700',
  },
  discountPill: {
    borderRadius: 8,
    backgroundColor: '#D9F5E2',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  discountPillText: {
    color: '#16794A',
    fontWeight: '900',
    fontSize: 17,
  },
  featureRow: {
    flexDirection: 'row',
    gap: 8,
  },
  featureChip: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingVertical: 8,
    paddingHorizontal: 8,
    alignItems: 'center',
    gap: 2,
  },
  featureIcon: {
    fontSize: 16,
    color: '#225C3D',
  },
  featureText: {
    fontSize: 18,
    color: '#1F2937',
    fontWeight: '700',
    textAlign: 'center',
  },
  detailEmi: {
    fontSize: 18,
    fontWeight: '800',
  },
  detailPlans: {
    color: '#146C2E',
    fontSize: 17,
    fontWeight: '900',
    textDecorationLine: 'underline',
  },
  capacityRow: {
    flexDirection: 'row',
    gap: 8,
  },
  capacityBtn: {
    flex: 1,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    alignItems: 'center',
  },
  capacityBtnActive: {
    borderColor: '#2E7D32',
    backgroundColor: '#F0FDF4',
  },
  capacityBtnDisabled: {
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
    opacity: 0.65,
  },
  capacityText: {
    color: '#374151',
    fontSize: 15,
    fontWeight: '700',
  },
  capacityTextDisabled: {
    color: '#9CA3AF',
  },
  capacityTextActive: {
    color: '#14532D',
    fontWeight: '900',
  },
  capacityUnavailableText: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '600',
  },
  detailAvailabilityBanner: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
    gap: 4,
  },
  detailAvailabilityTitle: {
    fontSize: 14,
    fontWeight: '800',
  },
  detailAvailabilityText: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
  },
  inCartIndicatorText: {
    color: '#166534',
    fontSize: 13,
    fontWeight: '700',
  },
  detailCtaRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  addCartBtn: {
    flex: 1,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#9CA3AF',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    paddingVertical: 12,
  },
  addCartBtnAdded: {
    borderColor: '#2E7D32',
    backgroundColor: '#ECFDF3',
  },
  addCartText: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  buyNowBtn: {
    flex: 1,
    borderRadius: 13,
    backgroundColor: '#2E8B1A',
    alignItems: 'center',
    paddingVertical: 12,
  },
  ctaBtnDisabled: {
    opacity: 0.5,
  },
  buyNowText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  ctaTextDisabled: {
    color: '#9CA3AF',
  },
  cartItemRow: {
    borderRadius: 14,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  cartItemImage: {
    width: 86,
    height: 64,
    borderRadius: 10,
    backgroundColor: '#E5E7EB',
  },
  cartItemInfo: {
    flex: 1,
    gap: 4,
  },
  cartItemPrice: {
    color: '#14532D',
    fontSize: 14,
    fontWeight: '900',
  },
  cartQtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cartQtyBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartQtyBtnText: {
    color: '#111827',
    fontSize: 15,
    lineHeight: 17,
    fontWeight: '900',
  },
  cartQtyValue: {
    minWidth: 18,
    textAlign: 'center',
    color: '#1F2937',
    fontSize: 13,
    fontWeight: '800',
  },
  cartRemoveText: {
    color: '#B91C1C',
    fontSize: 12,
    fontWeight: '700',
  },
  cartSummaryBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 10,
    gap: 6,
    marginTop: 4,
  },
  cartSummaryLabel: {
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '600',
  },
  cartSummaryValue: {
    color: '#111827',
    fontSize: 12,
    fontWeight: '700',
  },
  cartSummaryDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginVertical: 3,
  },
  cartSummaryTotalLabel: {
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '800',
  },
  cartSummaryTotalValue: {
    color: '#14532D',
    fontSize: 16,
    fontWeight: '900',
  },
  checkoutMainBtn: {
    marginTop: 8,
    borderRadius: 12,
    backgroundColor: '#1F7A35',
    alignItems: 'center',
    paddingVertical: 12,
  },
  checkoutMainBtnDisabled: {
    opacity: 0.6,
  },
  checkoutMainBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  checkoutPageSafe: {
    flex: 1,
    backgroundColor: '#F3F4F6',
  },
  checkoutHeader: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    backgroundColor: '#F3F4F6',
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkoutBackBtn: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkoutBackIcon: {
    fontSize: 28,
    lineHeight: 28,
    color: '#111827',
    fontWeight: '500',
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  checkoutHeaderTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#111827',
    fontSize: 34,
    lineHeight: 38,
    fontWeight: '900',
  },
  checkoutHeaderSpacer: {
    width: 34,
    height: 34,
  },
  checkoutPageContent: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 26,
    gap: 10,
  },
  checkoutPlacedBanner: {
    borderRadius: 10,
    backgroundColor: '#DCFCE7',
    borderWidth: 1,
    borderColor: '#86EFAC',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  checkoutPlacedText: {
    color: '#166534',
    fontSize: 13,
    fontWeight: '800',
  },
  checkoutEmptyState: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    gap: 10,
  },
  checkoutEmptyText: {
    color: '#374151',
    fontSize: 15,
    fontWeight: '600',
  },
  checkoutContinueBtn: {
    borderRadius: 10,
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    paddingVertical: 10,
  },
  checkoutContinueText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
  },
  checkoutListCard: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  checkoutLineItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 10,
  },
  checkoutLineImage: {
    width: 92,
    height: 74,
    borderRadius: 12,
    backgroundColor: '#E5E7EB',
  },
  checkoutLineMain: {
    flex: 1,
    gap: 4,
  },
  checkoutLineTitle: {
    color: '#111827',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '800',
  },
  checkoutLineSubtitle: {
    color: '#374151',
    fontSize: 14,
    fontWeight: '700',
  },
  checkoutQtyPill: {
    alignSelf: 'flex-start',
    borderRadius: 9,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkoutQtyText: {
    color: '#1F2937',
    fontSize: 13,
    fontWeight: '800',
  },
  checkoutQtyStepperBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkoutQtyStepperText: {
    color: '#111827',
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '800',
  },
  checkoutLinePrice: {
    color: '#111827',
    fontSize: 21,
    lineHeight: 24,
    fontWeight: '900',
  },
  checkoutLineRight: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    minHeight: 74,
    paddingTop: 28,
  },
  checkoutRemoveLink: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '500',
    textDecorationLine: 'underline',
  },
  checkoutLineDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 2,
  },
  checkoutTotalsCard: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 8,
  },
  checkoutSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  checkoutSummaryLabel: {
    color: '#1F2937',
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '600',
  },
  checkoutSummaryValue: {
    color: '#111827',
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '800',
  },
  checkoutSummaryValueDiscount: {
    color: '#166534',
  },
  checkoutSummaryValueDelivery: {
    color: '#15803D',
  },
  checkoutPlaceBtn: {
    borderRadius: 12,
    backgroundColor: '#2E8B1A',
    alignItems: 'center',
    paddingVertical: 13,
    marginTop: 2,
  },
  checkoutPlaceBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  checkoutModalSafe: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  checkoutBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(2, 6, 23, 0.45)',
  },
  checkoutSheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
    maxHeight: '85%',
  },
  checkoutAccountCard: {
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    padding: 10,
    gap: 3,
  },
  checkoutAccountTitle: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '800',
  },
  checkoutAccountSub: {
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '600',
  },
  checkoutItemsBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FAFAFA',
    padding: 10,
    gap: 8,
  },
  checkoutItemsTitle: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '800',
  },
  checkoutItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkoutItemName: {
    color: '#111827',
    fontSize: 12,
    fontWeight: '700',
  },
  checkoutItemSub: {
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '600',
  },
  checkoutItemQty: {
    color: '#14532D',
    fontSize: 12,
    fontWeight: '900',
  },
  checkoutCartStatusText: {
    color: '#166534',
    fontSize: 12,
    fontWeight: '700',
  },
  checkoutSuccessCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    backgroundColor: '#F0FDF4',
    padding: 10,
    gap: 8,
  },
  checkoutSuccessTitle: {
    color: '#14532D',
    fontSize: 15,
    fontWeight: '900',
  },
  checkoutSuccessSub: {
    color: '#166534',
    fontSize: 12,
    fontWeight: '600',
  },
  checkoutSuccessBtn: {
    marginTop: 4,
    borderRadius: 10,
    backgroundColor: '#166534',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  checkoutSuccessBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  checkoutInputGroup: {
    gap: 8,
  },
  checkoutInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 14,
  },
  profileSafe: {
    flex: 1,
  },
  profileHeader: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profileHeaderIconBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F4F6',
  },
  profileHeaderIcon: {
    fontSize: 22,
    lineHeight: 22,
    color: '#111827',
    fontWeight: '800',
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  profileHeaderTitle: {
    color: '#111827',
    fontSize: 33,
    lineHeight: 36,
    fontWeight: '900',
  },
  profileContent: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 20,
    gap: 10,
  },
  profileUserCard: {
    borderRadius: 18,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  profileAvatar: {
    width: 82,
    height: 82,
    borderRadius: 41,
    backgroundColor: '#E5E7EB',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  profileUserInfo: {
    flex: 1,
    gap: 1,
  },
  profileUserName: {
    color: '#111827',
    fontSize: 21,
    lineHeight: 24,
    fontWeight: '900',
  },
  profileUserMeta: {
    color: '#374151',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '600',
  },
  profileEditMiniBtn: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#F8FAF7',
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  profileEditMiniText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '800',
  },
  profileLogoutMiniBtn: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#B85C5C',
    backgroundColor: '#B85C5C',
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  profileLogoutMiniText: {
    color: '#FEE2E2',
    fontSize: 14,
    fontWeight: '800',
  },
  profileSectionTitle: {
    color: '#111827',
    fontSize: 17,
    fontWeight: '900',
    marginTop: 4,
  },
  profileSectionCard: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  profileMenuRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
  },
  profileMenuIcon: {
    width: 26,
    fontSize: 19,
    textAlign: 'center',
  },
  profileMenuLabel: {
    flex: 1,
    color: '#111827',
    fontSize: 17,
    fontWeight: '700',
  },
  profileMenuArrow: {
    color: '#6B7280',
    fontSize: 27,
    lineHeight: 27,
    fontWeight: '300',
  },
  profileMenuDivider: {
    height: 1,
    marginLeft: 50,
    backgroundColor: '#E5E7EB',
  },
  profileMenuRightText: {
    color: '#4B5563',
    fontSize: 14,
    fontWeight: '700',
    marginRight: 2,
  },
  profileToggleTrack: {
    width: 50,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#E5E7EB',
    paddingHorizontal: 3,
    justifyContent: 'center',
    marginLeft: 'auto',
  },
  profileToggleTrackActive: {
    backgroundColor: '#166534',
  },
  profileToggleKnob: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
    alignSelf: 'flex-start',
  },
  profileToggleKnobActive: {
    alignSelf: 'flex-end',
  },
  profilePanelSafe: {
    flex: 1,
    backgroundColor: '#F3F4F6',
  },
  profilePanelHeader: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profilePanelTitle: {
    color: '#111827',
    fontSize: 26,
    lineHeight: 30,
    fontWeight: '900',
  },
  profilePanelContent: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 24,
    gap: 12,
  },
  profilePanelCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
  },
  profilePanelEmpty: {
    color: '#6B7280',
    fontSize: 14,
    fontWeight: '600',
  },
  profilePanelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 4,
  },
  profilePanelMain: {
    color: '#111827',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '800',
  },
  profilePanelSub: {
    color: '#4B5563',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    marginTop: 1,
  },
  profilePanelAmount: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'right',
  },
  profilePanelStatus: {
    color: '#166534',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'right',
    marginTop: 2,
  },
  profileWishlistRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 6,
  },
  profileWishlistImage: {
    width: 66,
    height: 52,
    borderRadius: 10,
    backgroundColor: '#E5E7EB',
  },
  profilePanelLink: {
    color: '#166534',
    fontSize: 13,
    fontWeight: '800',
  },
  profilePanelLinkDanger: {
    color: '#B91C1C',
    fontSize: 13,
    fontWeight: '800',
    marginLeft: 10,
  },
  profilePanelBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: '#DCFCE7',
    color: '#166534',
    fontSize: 11,
    fontWeight: '800',
    overflow: 'hidden',
  },
  profilePanelPrimaryBtn: {
    marginTop: 2,
    borderRadius: 10,
    backgroundColor: '#166534',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
  },
  profilePanelPrimaryText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  profileServiceCard: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
  },
  profileServiceCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  profileServiceCardCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  profileServiceStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    flexShrink: 0,
  },
  profileServiceStatusText: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '800',
  },
  profileServiceActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  profileServiceSecondaryBtn: {
    minWidth: 132,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileServiceSecondaryText: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '800',
  },
  profileOrderRow: {
    alignItems: 'flex-start',
    paddingVertical: 8,
  },
  profileOrderCardLayout: {
    width: '100%',
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  profileOrderMainRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    width: '100%',
  },
  profileOrderCard: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 12,
  },
  profileOrderHeaderWrap: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  profileOrderHeroImage: {
    width: 68,
    height: 68,
    borderRadius: 16,
    backgroundColor: '#E5E7EB',
  },
  profileOrderHeaderContent: {
    flex: 1,
    gap: 6,
  },
  profileOrderHeaderTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  profileOrderStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  profileOrderStatusBadgeText: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '800',
  },
  profileOrderMetaLine: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  profileOrderMetaPills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  profileOrderMetaPill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  profileOrderMetaPillText: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '800',
  },
  profileOrderContent: {
    flex: 1,
    minWidth: 0,
  },
  profileOrderAside: {
    alignItems: 'flex-end',
    gap: 3,
    minWidth: 96,
    flexShrink: 0,
  },
  profileOrderTotalBlock: {
    minWidth: 84,
    alignItems: 'flex-end',
    gap: 4,
  },
  profileOrderTotalLabel: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '700',
  },
  profileOrderOpenHint: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '800',
  },
  profileOrderMetaText: {
    color: '#1D4ED8',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '800',
    marginTop: 5,
  },
  profileOrderTaxHint: {
    color: '#166534',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '800',
    marginTop: 4,
  },
  profileOrderExpandableBlock: {
    marginTop: 10,
    gap: 8,
  },
  profileOrderExpandToggle: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  profileOrderExpandCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  profileOrderExpandTitle: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '900',
  },
  profileOrderExpandSubtext: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '600',
  },
  profileOrderExpandCountBadge: {
    minWidth: 38,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  profileOrderExpandCountText: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '900',
  },
  profileOrderExpandChevron: {
    fontSize: 15,
    lineHeight: 17,
    fontWeight: '900',
    flexShrink: 0,
  },
  profileOrderItemsSection: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 10,
  },
  profileOrderFeaturedItem: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 8,
  },
  profileOrderFeaturedBody: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  profileOrderExtraItems: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 4,
  },
  profileOrderExtraItemsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  profileOrderExtraItemsCount: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '800',
  },
  profileOrderSectionLabel: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  profileOrderExtraItemRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 9,
  },
  profileOrderExtraItemCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  profileOrderExtraItemName: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '700',
  },
  profileOrderExtraItemMeta: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '600',
  },
  profileOrderExtraItemAmount: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '900',
    textAlign: 'right',
    flexShrink: 0,
  },
  profileOrderItemsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  profileOrderItemsTitle: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '900',
  },
  profileOrderItemsCount: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '700',
  },
  profileOrderItemCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingTop: 10,
  },
  profileOrderItemThumb: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: '#E5E7EB',
  },
  profileOrderItemContent: {
    flex: 1,
    gap: 4,
  },
  profileOrderItemTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '800',
  },
  profileOrderItemMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  profileOrderItemFooter: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  profileOrderQtyBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  profileOrderQtyBadgeText: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '800',
  },
  profileOrderItemPrice: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '900',
  },
  profileOrderFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  profileOrderFooterText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
  },
  orderDetailSafe: {
    flex: 1,
  },
  orderDetailHeader: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  orderDetailHeaderTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '900',
  },
  orderDetailHeaderAction: {
    minWidth: 44,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderDetailHeaderActionText: {
    fontSize: 12,
    fontWeight: '900',
  },
  orderDetailContent: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 14,
  },
  orderDetailCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    gap: 12,
  },
  orderDetailOrderNumber: {
    fontSize: 26,
    lineHeight: 30,
    fontWeight: '900',
  },
  orderDetailStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  orderDetailStatusIcon: {
    fontSize: 16,
    fontWeight: '900',
  },
  orderDetailStatusText: {
    fontSize: 15,
    fontWeight: '900',
  },
  orderDetailMeta: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  orderDetailSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  orderDetailSectionTitle: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '900',
  },
  orderDetailSectionMeta: {
    fontSize: 12,
    fontWeight: '700',
  },
  orderDetailItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingTop: 12,
    borderTopWidth: 1,
  },
  orderDetailItemImage: {
    width: 86,
    height: 86,
    borderRadius: 16,
    backgroundColor: '#E5E7EB',
  },
  orderDetailItemMain: {
    flex: 1,
    gap: 3,
  },
  orderDetailItemTitle: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '900',
  },
  orderDetailItemSub: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  orderDetailItemQty: {
    fontSize: 12,
    fontWeight: '700',
  },
  orderDetailItemAmount: {
    fontSize: 16,
    fontWeight: '900',
    marginTop: 2,
  },
  orderDetailItemButton: {
    minWidth: 116,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  orderDetailItemButtonText: {
    fontSize: 13,
    fontWeight: '900',
  },
  orderDetailInlineBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  orderDetailInlineBadgeText: {
    fontSize: 11,
    fontWeight: '900',
  },
  orderDetailAddressName: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '900',
  },
  orderDetailAddressText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  orderDetailAddressPhone: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
  },
  orderDetailSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  orderDetailSummaryLabel: {
    fontSize: 14,
    fontWeight: '700',
  },
  orderDetailSummaryNote: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    marginTop: 4,
  },
  orderDetailSummaryValue: {
    fontSize: 14,
    fontWeight: '900',
  },
  orderDetailSummaryAccent: {
    fontSize: 14,
    fontWeight: '900',
  },
  orderDetailSummaryTotalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderTopWidth: 1,
    paddingTop: 12,
    marginTop: 2,
  },
  orderDetailSummaryTotalLabel: {
    fontSize: 18,
    fontWeight: '900',
  },
  orderDetailSummaryTotalValue: {
    fontSize: 18,
    fontWeight: '900',
  },
  orderDetailSummaryFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  orderDetailPaymentStatus: {
    fontSize: 14,
    fontWeight: '900',
  },
  orderDetailPaymentNote: {
    flex: 1,
    textAlign: 'right',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  orderDetailNoteText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
  },
  orderDetailNoteSubtext: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  orderDetailActionRow: {
    gap: 10,
    paddingBottom: 10,
  },
  orderDetailPrimaryBtn: {
    borderRadius: 999,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  orderDetailPrimaryBtnText: {
    fontSize: 15,
    fontWeight: '900',
  },
  orderDetailSecondaryBtn: {
    borderRadius: 999,
    minHeight: 50,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  orderDetailSecondaryBtnText: {
    fontSize: 15,
    fontWeight: '900',
  },
  invoiceSafe: {
    flex: 1,
  },
  invoiceHeader: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  invoiceHeaderTitle: {
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '900',
  },
  invoiceContent: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 14,
  },
  invoicePaper: {
    borderRadius: 24,
    backgroundColor: '#FFFDF8',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 16,
    gap: 16,
  },
  invoiceHero: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  invoiceEyebrow: {
    color: '#0F766E',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  invoiceNumber: {
    color: '#111827',
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '900',
    marginTop: 4,
  },
  invoiceSubhead: {
    color: '#4B5563',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    marginTop: 6,
  },
  invoiceStatusPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  invoiceStatusText: {
    fontSize: 12,
    fontWeight: '900',
  },
  invoiceHighlightRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  invoiceHighlightCard: {
    flexGrow: 1,
    flexBasis: 0,
    minWidth: 140,
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
    padding: 12,
    gap: 6,
  },
  invoiceHighlightLabel: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '800',
  },
  invoiceHighlightValue: {
    color: '#0F172A',
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '900',
  },
  invoicePartyGrid: {
    gap: 10,
  },
  invoicePartyCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    padding: 12,
    gap: 5,
  },
  invoicePartyTitle: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  invoicePartyName: {
    color: '#111827',
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '900',
  },
  invoicePartyText: {
    color: '#475569',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  invoiceSection: {
    gap: 10,
  },
  invoiceSectionTitle: {
    color: '#111827',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '900',
  },
  invoiceLineCard: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
    gap: 10,
  },
  invoiceLineHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  invoiceLineTitle: {
    color: '#111827',
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '900',
  },
  invoiceLineDesc: {
    color: '#475569',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
    marginTop: 3,
  },
  invoiceLineAmount: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '900',
  },
  invoiceLineMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  invoiceLineMeta: {
    color: '#475569',
    fontSize: 11,
    fontWeight: '800',
    backgroundColor: '#F8FAFC',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 5,
    overflow: 'hidden',
  },
  invoiceLineBreakdown: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  invoiceMiniStat: {
    minWidth: 110,
    flexGrow: 1,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  invoiceMiniStatLabel: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '800',
  },
  invoiceMiniStatValue: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '900',
  },
  invoiceTaxSplitText: {
    color: '#0F766E',
    fontSize: 12,
    fontWeight: '800',
  },
  invoiceTotalsCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    padding: 14,
    gap: 10,
  },
  invoiceTotalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  invoiceTotalLabel: {
    color: '#475569',
    fontSize: 13,
    fontWeight: '700',
  },
  invoiceTotalValue: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '900',
  },
  invoiceTotalRowGrand: {
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
    marginTop: 2,
  },
  invoiceGrandLabel: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '900',
  },
  invoiceGrandValue: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '900',
  },
  invoiceNoteCard: {
    borderRadius: 18,
    backgroundColor: '#E0F2FE',
    padding: 14,
    gap: 8,
  },
  invoiceNoteTitle: {
    color: '#0C4A6E',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  invoiceNoteText: {
    color: '#0F172A',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
  },
  invoiceFootnote: {
    color: '#155E75',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },
  profileLanguageRow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#F8FAFC',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 11,
  },
  profileLanguageRowActive: {
    borderColor: '#86EFAC',
    backgroundColor: '#ECFDF5',
  },
  profileEditBackdrop: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 16,
    backgroundColor: 'rgba(2, 6, 23, 0.45)',
  },
  profileEditCard: {
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 14,
    gap: 10,
  },
  profileEditCardTall: {
    maxHeight: '92%',
  },
  profileEditScrollContent: {
    gap: 10,
    paddingBottom: 4,
  },
  profileEditTitle: {
    color: '#111827',
    fontSize: 21,
    fontWeight: '900',
  },
  profileEditInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    color: '#111827',
    paddingHorizontal: 11,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: '600',
  },
  profileEditActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  profileEditCancelBtn: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  profileEditCancelText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
  },
  profileEditSaveBtn: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: '#166534',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  profileEditSaveText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  viewMoreModalSafe: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  viewMoreBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(2, 6, 23, 0.45)',
  },
  viewMoreWindow: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 10,
    maxHeight: '85%',
  },
  viewMoreList: {
    marginTop: 6,
  },
  viewMoreListContent: {
    paddingBottom: 22,
    gap: 10,
  },
  landingFooter: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  footerItem: {
    width: 62,
    alignItems: 'center',
    gap: 2,
  },
  footerIcon: {
    color: '#1F2937',
    fontSize: 18,
  },
  footerCartWrap: {
    position: 'relative',
    paddingHorizontal: 2,
  },
  footerCartBadge: {
    position: 'absolute',
    top: -5,
    right: -10,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#B91C1C',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  footerCartBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
  },
  footerCenter: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerCenterText: {
    fontSize: 30,
    lineHeight: 30,
    fontWeight: '700',
  },
  feedbackHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  feedbackTitle: {
    fontSize: 46,
    lineHeight: 50,
    fontWeight: '900',
    marginTop: -2,
  },
  feedbackBanner: {
    borderRadius: 24,
    minHeight: 278,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#0F172A',
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  feedbackBannerImage: {
    width: '100%',
    height: '100%',
    minHeight: 278,
    backgroundColor: '#334155',
  },
  feedbackBannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(2, 6, 23, 0.40)',
  },
  feedbackBannerContent: {
    position: 'absolute',
    left: 18,
    top: 18,
    right: 18,
    gap: 12,
  },
  feedbackBannerHeading: {
    color: '#FFFFFF',
    fontSize: 38,
    lineHeight: 43,
    fontWeight: '900',
    maxWidth: '88%',
  },
  feedbackStarsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  feedbackStarBtn: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.28)',
  },
  feedbackStar: {
    fontSize: 35,
    lineHeight: 35,
    fontWeight: '900',
  },
  feedbackStarActive: {
    color: '#FACC15',
  },
  feedbackStarInactive: {
    color: '#CBD5E1',
  },
  feedbackPrompt: {
    marginTop: 6,
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '800',
  },
  feedbackInput: {
    borderWidth: 1,
    borderRadius: 20,
    minHeight: 118,
    paddingHorizontal: 15,
    paddingVertical: 14,
    fontSize: 19,
    lineHeight: 25,
    fontWeight: '600',
  },
  feedbackSubmitBtn: {
    marginTop: 4,
    borderRadius: 999,
    backgroundColor: '#1E7B39',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    shadowColor: '#14532D',
    shadowOpacity: 0.27,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  feedbackSubmitText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '900',
  },
  feedbackCaption: {
    marginTop: 2,
    marginBottom: 4,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '600',
  },
  feedbackBenefitStrip: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingVertical: 13,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  feedbackBenefitItem: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 4,
  },
  feedbackBenefitIcon: {
    fontSize: 29,
    lineHeight: 31,
  },
  feedbackBenefitText: {
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  feedbackBenefitDivider: {
    width: 1,
    alignSelf: 'stretch',
    opacity: 0.8,
    marginHorizontal: 4,
  },
  itemText: { fontSize: scaleFont(13), fontWeight: '700' },
});


export default styles;
